export type AssociationDirectoryEntry = {
  street: string;
  association: string;
  code: string;
  chairman?: string;
  phone?: string;
};

/** Authoritative BERA three-letter street identification directory. */
export const ASSOCIATION_DIRECTORY: AssociationDirectoryEntry[] = [
  { street: 'Arigidi Street', association: 'Arigidi', code: 'ASA', chairman: 'Chief Adeniyi', phone: '08033236428' },
  { street: 'Arigidi Close', association: 'Arigidi', code: 'ACA' },
  { street: 'Canon Akinyemi Street', association: 'Arigidi', code: 'CAA' },
  { street: 'Awogboro Street', association: 'Peace Lover', code: 'ASP', chairman: 'Mr. Lanre Ayodeji', phone: '08099118993' },
  { street: 'Afolabi Durotoye', association: 'Peace Lover', code: 'ADP' },
  { street: 'Oba Oyewusi', association: 'Peace Lover', code: 'OOP' },
  { street: 'Gbenro Ogunbiyi', association: 'Peace Lover', code: 'GOP' },
  { street: 'Awosika', association: 'Awosika', code: 'AWW', chairman: 'Engr. Kolade', phone: '08033022395' },
  { street: 'Arulogun Close', association: 'Awosika', code: 'ACW' },
  { street: 'Ogboriefon Close', association: 'Awosika', code: 'OCW' },
  { street: 'Alayande Close', association: 'Awosika', code: 'ALW' },
  { street: 'Rotimi Williams Avenue', association: 'Awosika', code: 'RWW' },
  { street: 'Oba Akinyele Avenue', association: 'Awosika', code: 'OAW' },
  { street: 'Ilaro Street', association: 'Ilaro/Ikare/Ede/Alabiamo', code: 'ISI', chairman: 'Mr. Niyi Andu', phone: '08023780280' },
  { street: 'Ikare Street', association: 'Ilaro/Ikare/Ede/Alabiamo', code: 'IKI' },
  { street: 'Ede Street', association: 'Ilaro/Ikare/Ede/Alabiamo', code: 'ESI' },
  { street: 'Alabiamo Street', association: 'Ilaro/Ikare/Ede/Alabiamo', code: 'ASI' },
  { street: 'Oba Olagbegi', association: 'Oba Olagbegi', code: 'OLO', chairman: 'Oluwatay Moses', phone: '08061138803' },
  { street: 'University Crescent', association: 'Oba Olagbegi', code: 'UCO' },
  { street: 'Ojo Badan', association: 'Oba Olagbegi', code: 'OBO' },
  { street: 'Oba Akenzua Avenue', association: 'Oba Olagbegi', code: 'OAO' },
  { street: 'Ondo Street', association: 'Ondo Street', code: 'ONT', chairman: 'Mr. Olutayo Adegbemle', phone: '08033515059' },
  { street: 'Ondo Close', association: 'Ondo Street', code: 'OCT' },
  { street: 'Oshuntokun Road', association: 'Oshuntokun', code: 'OSR' },
  { street: 'Rev. Aderinola Close', association: 'Dejo Oyelese Vigilante Group (DOVG)', code: 'RCD', chairman: 'HE Iyiola Oladokun', phone: '08022908167' },
  { street: 'Rev. Aderinola Street', association: 'Dejo Oyelese Vigilante Group (DOVG)', code: 'RSD' },
  { street: 'Akinlabi Sanda Close', association: 'Dejo Oyelese Vigilante Group (DOVG)', code: 'ASD' },
  { street: 'Beckley Street', association: 'Dejo Oyelese Vigilante Group (DOVG)', code: 'BSD' },
  { street: 'Canon Odusanwo Close', association: 'Dejo Oyelese Vigilante Group (DOVG)', code: 'COD' },
  { street: 'Dejo Oyelese Street', association: 'Dejo Oyelese Vigilante Group (DOVG)', code: 'DOD' },
  { street: 'Obasanmi Olakanpo Close', association: 'Dejo Oyelese Vigilante Group (DOVG)', code: 'OCD' },
  { street: 'Obasanmi Olakanpo Street', association: 'Dejo Oyelese Vigilante Group (DOVG)', code: 'OSD' },
  { street: 'Oranmiyan Street', association: 'Dejo Oyelese Vigilante Group (DOVG)', code: 'ORD' },
  { street: 'Tunde Lakanmi', association: 'Dejo Oyelese Vigilante Group (DOVG)', code: 'TLD' },
  { street: 'Ekiti Street', association: 'Ekiti/Osun', code: 'ESE', chairman: 'Dn. C.O Oke', phone: '08033861091' },
  { street: 'Osun Street', association: 'Ekiti/Osun', code: 'OSE' },
  { street: 'Osun Close', association: 'Ekiti/Osun', code: 'OCE' },
  { street: 'Osun Lane', association: 'Ekiti/Osun', code: 'OLE' },
  { street: 'Francis Okediji', association: 'Francis Okediji', code: 'FOK' },
  { street: 'Ibikunle Avenue', association: 'Ibikunle/Oyeshina', code: 'IAB', chairman: 'Mr. Lambo' },
  { street: 'Oyeshina Close', association: 'Ibikunle/Oyeshina', code: 'OCB' },
  { street: 'Lower Adeyi', association: 'Lower Adeyi', code: 'LAL' },
  { street: 'Oduduwa', association: 'Lower Adeyi', code: 'ODL' },
  { street: 'Upper Adeyi', association: 'Upper Adeyi', code: 'UAD' },
  { street: 'Ekiti Close', association: 'Ekiti Close', code: 'EKC', chairman: 'Mrs Balogun', phone: '09026838651' },
  { street: 'Abiodun Akerele', association: 'Abiodun Akerele', code: 'ABK' },
  { street: 'Oluokukun', association: 'Oluokukun', code: 'OLK' },
  { street: 'Oluyoro', association: 'Oluyoro', code: 'OLY' },
  { street: 'Aperin', association: 'Aperin', code: 'APE' },
  { street: 'Aare Avenue', association: 'Aare Avenue', code: 'AAV' },
  { street: 'Adigun Road', association: 'Adigun Road', code: 'ADR' },
  { street: 'Paul Hendricks', association: 'Pholask', code: 'PHH' },
  { street: 'Saka Agbaje Street', association: 'Pholask', code: 'SAH' },
  { street: 'Lagelu Close', association: 'Pholask', code: 'LCH' },
  { street: 'Obe Street', association: 'Obe Street', code: 'OBS' },
  { street: 'Adebajo Street', association: 'Adebajo Street', code: 'ABS' },
  { street: 'Adenuga Street', association: 'Adenuga Street', code: 'ASN' },
  { street: 'Lala Avenue', association: 'Adenuga Street', code: 'LAN' },
  { street: 'Lucas Street', association: 'Adenuga Street', code: 'LSN' },
  { street: 'Funto Luca Avenue', association: 'Adenuga Street', code: 'FLN' },
  { street: 'Ademiluyi Close', association: 'Ademiluyi Close', code: 'ADC', chairman: 'Mr. James Ashidi', phone: '08023145181' },
  { street: 'Oke Badan Crescent', association: 'Oke Badan Crescent', code: 'OBC' },
  { street: 'Aaretedo', association: 'Aaretedo', code: 'ART', chairman: 'Engr. Majasan', phone: '08059611555' },
  { street: 'Moremi', association: 'Moremi Ogunsola', code: 'MOR', chairman: 'Dr. Gabriel Oluyemi', phone: '09118024664' },
  { street: 'Ladoke Akintola', association: 'Okunola/Ladoke Akintola', code: 'LAK' },
  { street: 'Okunola Abbas', association: 'Okunola/Ladoke Akintola', code: 'OAK' },
  { street: 'Olubi Close', association: 'Okunola/Ladoke Akintola', code: 'OCK' },
  { street: 'Ayo Adekunle', association: 'Okunola/Ladoke Akintola', code: 'AAK' },
  { street: 'Oluyole Way', association: 'Okunola/Ladoke Akintola', code: 'OWK' },
  { street: 'Ibrahim Taiwo', association: 'Okunola/Ladoke Akintola', code: 'ITK' },
  { street: 'Osuade Adeleke', association: 'Okunola/Ladoke Akintola', code: 'ODK' },
  { street: 'Sariyu Adebisi (SKA)', association: 'Sariyu Adebisi (SKA)', code: 'SKA' },
  { street: 'Soun Ajagungbade', association: 'Soun Ajagungbade', code: 'SOA' },
  { street: 'Olusola Adeshina Close', association: 'Olusola Adeshina Close', code: 'OAC' },
  { street: 'Alh. Kunle Abass Close', association: 'Alh. Kunle Abass Close', code: 'KAC' },
  { street: 'Selamon Street', association: 'Selamon Street', code: 'SEL' },
  { street: 'Akinsehinwa Street', association: 'Akinsehinwa Street', code: 'AKS' },
  { street: 'Oluyole Way', association: 'Oluyole Way', code: 'OLW' },
  { street: 'Atiba Street', association: 'Atiba Street', code: 'ATS' },
  { street: 'Kenneth Dike', association: 'Kenneth Dike', code: 'KDI' },
  { street: 'Awolowo Avenue', association: 'Awolowo Avenue', code: 'AWO' },
];
