export type AssociationDirectoryEntry = {
  street: string;
  association?: string;
  chairman?: string;
  phone?: string;
};

export const ASSOCIATION_DIRECTORY: AssociationDirectoryEntry[] = [
  { street: 'Arigidi Street', association: 'Arigidi', chairman: 'Chief Adeniyi', phone: '08033236428' },
  { street: 'Arigidi Close', association: 'Arigidi' },
  { street: 'Ondo Street', association: 'Arigidi' },
  { street: 'Canon Akinyemi Street', association: 'Arigidi' },
  { street: 'Awogboro/Peace Lover', association: 'Awogboro/Peace Lover', chairman: 'Mr. Lanre Ayodeji', phone: '08099118993' },
  { street: 'Awosika', association: 'Awosika', chairman: 'Engr. Kolade', phone: '08033022395' },
  { street: 'Ilaro Street', association: 'Ilaro/Ikare/Ede/Alabiamo', chairman: 'Mr. Niyi Andu', phone: '08023780280' },
  { street: 'Ikare Street', association: 'Ilaro/Ikare/Ede/Alabiamo' },
  { street: 'Ede Street', association: 'Ilaro/Ikare/Ede/Alabiamo' },
  { street: 'Alabiamo Street', association: 'Ilaro/Ikare/Ede/Alabiamo' },
  { street: 'Alabiamo Avenue', association: 'Ilaro/Ikare/Ede/Alabiamo' },
  { street: 'Oba Olagbegi', association: 'Oba Olagbegi', chairman: 'Oluwatay Moses', phone: '08061138803' },
  { street: 'Rotimi Williams Avenue', association: 'Oba Olagbegi' },
  { street: 'University Crescent', association: 'Oba Olagbegi' },
  { street: 'Ojo Badan', association: 'Oba Olagbegi' },
  { street: 'Arulogun Close', association: 'Oba Olagbegi' },
  { street: 'Oba Akenzua Avenue', association: 'Oba Olagbegi' },
  { street: 'Ondo Street', association: 'Ondo Street', chairman: 'Mr. Olutayo Adegbemle', phone: '08033515059' },
  { street: 'Oshuntokun Road', association: 'Oshuntokun' },
  { street: 'Tunde Lakanmi', association: 'Oshuntokun' },
  { street: 'Gbenro Ogunsuyi Street', association: 'Oshuntokun' },
  { street: 'Abiodun Akerele', association: 'Abiodun Akerele' },
  { street: 'Rev. Aderinola Close', association: 'DOVG', chairman: 'HE Iyiola Oladokun', phone: '08022908167' },
  { street: 'Rev. Aderinola Street', association: 'DOVG' },
  { street: 'Akinlabi Sanda Close', association: 'DOVG' },
  { street: 'Beckley Street', association: 'DOVG' },
  { street: 'Canon Odusanwo Close', association: 'DOVG' },
  { street: 'Dejo Oyelese Street', association: 'DOVG' },
  { street: 'Obasanmi Olakanpo Close', association: 'DOVG' },
  { street: 'Obasanmi Olakanpo Street', association: 'DOVG' },
  { street: 'Oranmiyan Street', association: 'DOVG' },
  { street: 'Ekiti Street', association: 'Ekiti/Osun', chairman: 'Dn. C.O Oke', phone: '08033861091' },
  { street: 'Osun Street', association: 'Ekiti/Osun' },
  { street: 'Ekiti Close', association: 'Ekiti Close', chairman: 'Mrs Balogun', phone: '09026838651' },
  { street: 'Francis Okediji', association: 'Francis Okediji' },
  { street: 'Ibikunle Avenue', association: 'Ibikunle/Oyeshina', chairman: 'Mr. Lambo' },
  { street: 'Oyeshina Close', association: 'Ibikunle/Oyeshina' },
  { street: 'Lower Adeyi', association: 'Lower Adeyi' },
  { street: 'Oduduwa', association: 'Lower Adeyi' },
  { street: 'Upper Adeyi', association: 'Upper Adeyi' },
  { street: 'Oluyoro', association: 'Oluyoro' },
  { street: 'Aperin', association: 'Aperin' },
  { street: 'Aare Avenue', association: 'Aare Avenue' },
  { street: 'Adigun Road', association: 'Aare Avenue' },
  { street: 'Saka Agbaje Street', association: 'Aare Avenue' },
  { street: 'Paul Hendricks', association: 'Aare Avenue' },
  { street: 'Lagelu Close', association: 'Aare Avenue' },
  { street: 'Obe Street', association: 'Aare Avenue' },
  { street: 'Adebajo Street', association: 'Aare Avenue' },
  { street: 'Adebajo Crescent', association: 'Aare Avenue' },
  { street: 'Adenuga Crescent', association: 'Aare Avenue' },
  { street: 'Lala Avenue', association: 'Aare Avenue' },
  { street: 'Funto Luca Avenue', association: 'Aare Avenue' },
  { street: 'Oke Badan Crescent' },
  { street: 'Aretedo', association: 'Aretedo', chairman: 'Engr. Majasan', phone: '08059611555' },
  { street: 'Pholask', association: 'Pholask' },
  { street: 'Moremi', association: 'Moremi', chairman: 'Dr. Gabriel Oluyemi', phone: '09118024664' },
  { street: 'Ladoke Akintola', association: 'Okunola/Ladoke Akintola' },
  { street: 'Okunola', association: 'Okunola/Ladoke Akintola' },
  { street: 'Olubi Close', association: 'Okunola/Ladoke Akintola' },
  { street: 'Ayo Adekunle', association: 'Okunola/Ladoke Akintola' },
  { street: 'Oluyole Way', association: 'Okunola/Ladoke Akintola' },
  { street: 'Ibrahim Taiwo', association: 'Okunola/Ladoke Akintola' },
  { street: 'Osuade Adeleke', association: 'Okunola/Ladoke Akintola' },
  { street: 'Ademiluyi Close', association: 'Ademiluyi Close', chairman: 'Mr. James Ashidi', phone: '08023145181' },
  { street: 'Moremi Crescent' },
  { street: 'Sariyu Adebisi (SKA)' },
  { street: 'Soun Ajagungbade', association: 'Soun Ajagungbade' },
  { street: 'Olusola Adeshina Close' },
  { street: 'Alh. Kunle Abass Close' },
  { street: 'Selamon Street' },
  { street: 'Akinsehinwa Street' },
  { street: 'Oluyole Way' },
  { street: 'Atiba Street' },
  { street: 'Kenneth Dike', association: 'Kenneth Dike' },
  { street: 'Awolowo Avenue', association: 'Awolowo Avenue' },
];
